### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Liangbai2333** [nexusnode/crafting-dead#218]
It happens while spawning some zombie entities on the server.

I tried that the capability was null.

`
Cause of unexpected exception was
java.lang.IllegalStateException: Expecting capability: com/craftingdead/core/world/entity/extension/LivingExtension
	at com.craftingdead.core.capability.CapabilityUtil.getOrThrow(CapabilityUtil.java:47) ~[crafting-dead-core-1.18.2-1.7.6-alpha(1)(1).jar%2370!/:1.7.6-alpha] {re:classloading}
	at com.craftingdead.core.world.entity.extension.LivingExtension.getOrThrow(LivingExtension.java:61) ~[crafting-dead-core-1.18.2-1.7.6-alpha(1)(1).jar%2370!/:1.7.6-alpha] {re:mixin,re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.m_6518_(AdvancedZombie.java:300) ~[crafting-dead-survival-1.18.2-1.1.9-alpha(2).jar%2371!/:1.1.9-alpha] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.WeakZombie.m_6518_(WeakZombie.java:51) ~[crafting-dead-survival-1.18.2-1.1.9-alpha(2).jar%2371!/:1.1.9-alpha] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(WorldEntitySpawnerMixin.java:186) ~[server-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.spawner.WorldEntitySpawnerMixin,pl:mixin:A}
`

Running server: Arclight, Forge: 40.1.59

**Comment by Liangbai2333** [comment]
By the way, in survival, the handleRightClickItem method in CraftingDeadSurvival class, where a null is passed in the performAction/decode method, will cause a crash.

**Comment by 0xE69** [comment]
Hello, 

Yes, We have had the same issues too. This is due to a later version of arclight. 

@Sm0keySa1m0n  Can you provide some extra information on this.

**Comment by PatalJunior** [comment]
I have same issue, it happens more frequently with more players.
Not sure, but my friend seemed to notice when he hears the gun sound (when police zombie spawns), and a few seconds after crashes.

I'm running a plain forge server, nothing more

[crash-2022-07-27_21.41.42-server.txt](https://github.com/nexusnode/crafting-dead/files/9208414/crash-2022-07-27_21.41.42-server.txt)

**Comment by PatalJunior** [comment]
I'm using spawners to spawn the zombies on buildings, not sure if that would make any difference.

And in the client size sometimes it throws this error out as well :
java.lang.IllegalStateException: no magazine capacity

**Comment by PatalJunior** [comment]
Does anybody have new info on this, at the moment is infeasible to run a crafting dead server because of this issue.

**Comment by josephtarbit** [comment]
@PatalJunior Is this still occurring in the latest version of the mod?
