### ISSUE TITLE
Game crashes on startup with survival added

### ISSUE THREAD

**Issue by LustrousBlue** [nexusnode/crafting-dead#239]
Upon worldgen, the game crashes instantly once it finishes, tried with various versions, all seem to be the same. 

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11/16/22, 11:33 AM
Description: Exception ticking world

java.lang.NoSuchFieldError: ITEMS
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.getRandomItem(AdvancedZombie.java:218) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.createClothingItem(AdvancedZombie.java:205) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.lambda$populateDefaultEquipmentSlots$3(AdvancedZombie.java:192) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.68-universal.jar%2361!/:?] {re:mixin,re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.m_6851_(AdvancedZombie.java:190) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at net.minecraft.world.entity.monster.Zombie.m_6518_(Zombie.java:447) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.m_6518_(AdvancedZombie.java:289) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.WeakZombie.m_6518_(WeakZombie.java:48) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:186) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:126) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:309) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:281) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.getRandomItem(AdvancedZombie.java:218) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.createClothingItem(AdvancedZombie.java:205) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.lambda$populateDefaultEquipmentSlots$3(AdvancedZombie.java:192) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.68-universal.jar%2361!/:?] {re:mixin,re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.m_6851_(AdvancedZombie.java:190) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at net.minecraft.world.entity.monster.Zombie.m_6518_(Zombie.java:447) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.AdvancedZombie.m_6518_(AdvancedZombie.java:289) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at com.craftingdead.survival.world.entity.monster.WeakZombie.m_6518_(WeakZombie.java:48) ~[crafting-dead-survival-1.18.2-1.1.8-alpha.jar%2354!/:1.1.8-alpha] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:186) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:126) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:309) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:281) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['epicninja532'/193, l='ServerLevel[New World]', x=-8.50, y=102.00, z=5.50]]
	Chunk stats: 2252
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,99,0), Section: (at 0,3,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 81 game time, 81 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 159810 (now: false), thunder time: 93544 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 443180816 bytes (422 MiB) / 1577058304 bytes (1504 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x249d
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a60
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1340
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30989.10
	Virtual memory used (MB): 25273.86
	Swap memory total (MB): 14903.60
	Swap memory used (MB): 1311.61
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['epicninja532'/193, l='ServerLevel[New World]', x=-8.50, y=102.00, z=5.50]]
	Data Packs: vanilla, mod:forge, mod:curios (incompatible), mod:craftingdeadsurvival (incompatible), mod:craftingdead (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.1.68-universal.jar                |Forge                         |forge                         |40.1.68             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
		crafting-dead-survival-1.18.2-1.1.8-alpha.jar     |Crafting Dead Survival        |craftingdeadsurvival          |1.1.8-alpha         |DONE      |Manifest: NOSIGNATURE
		crafting-dead-core-1.18.2-1.7.6-alpha.jar         |Crafting Dead                 |craftingdead                  |1.7.6-alpha         |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d85232a1-3b53-44ce-9d17-16e2a0937672
	FML: 40.1
	Forge: net.minecraftforge:40.1.68

**Comment by josephtarbit** [comment]
Update core
